### ISSUE TITLE
Multiple tags preselected - issue whith height adjustment

### ISSUE THREAD

**Issue by Caimilan** [kanakiyajay/popSelect#3]
if more elements pre-selected as fit in 1 line, the height adjustment does not work.
Have a look at the screenshot below.
<img width="568" alt="screenshot at mai 05 10-43-44" src="https://cloud.githubusercontent.com/assets/18400500/15039559/4f00e446-12ae-11e6-81d9-5ce422bff6e3.png">

**Comment by kanakiyajay** [comment]
Should be solved with c3da236
